#!/bin/bash
# 2009 Matt Brubeck
# License:  GPL, http://www.gnu.org/copyleft/gpl.html
case $1 in
"usage")
  echo "$(basename $0) [BASENAME]"
  echo "  Open \$TODO_DIR/BASENAME.txt in \$EDITOR."
  echo "  If BASENAME is not given, defaults to 'todo'."
  ;;
*)
  file=
  case "x$2" in
    "xdone")
      file="$DONE_FILE"
      ;;
    "xreport")
      file="$REPORT_FILE"
      ;;
    "xtodo"|"x")
      file="$TODO_FILE"
      ;;
    *)
      file="$TODO_DIR/$2.txt"
      ;;
  esac
  $EDITOR "$file"
  ;;
esac
